import moment from 'moment'
export default {
    newProducts: [
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 1).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/04/Diaphragm-Pumps-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 2).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 3).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 1).valueOf(),
            inStock: 15,
            clicked: 1,

        },
    ],
    recommendations: [
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/04/Diaphragm-Pumps-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 32).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/5.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 31).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 30).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 29).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 28).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            // image: require('../assets/frontendimages/5.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 27).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 26).valueOf(),
            inStock: 15,
            clicked: 1,

        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 25).valueOf(),
            inStock: 15,
            clicked: 1,

        },
    ],
    allProducts: [
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/04/Diaphragm-Pumps-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 24).valueOf(),
            inStock: 15,
            clicked: 1,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/5.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 23).valueOf(),
            inStock: 15,
            clicked: 2,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 22).valueOf(),
            inStock: 15,
            clicked: 3,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 21).valueOf(),
            inStock: 15,
            clicked: 4,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 20).valueOf(),
            inStock: 15,
            clicked: 5,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            // image: require('../assets/frontendimages/5.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 19).valueOf(),
            inStock: 15,
            clicked: 6,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 18).valueOf(),
            inStock: 15,
            clicked: 7,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 17).valueOf(),
            inStock: 15,
            clicked: 8,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 16).valueOf(),
            inStock: 15,
            clicked: 9,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/04/Diaphragm-Pumps-300x300.png",
            price: 250,
            title: "Wire",
            createdAt: moment().subtract('day', 15).valueOf(),
            inStock: 15,
            clicked: 10,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 14).valueOf(),
            inStock: 15,
            clicked: 11,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 13).valueOf(),
            inStock: 15,
            clicked: 12,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/04/Diaphragm-Pumps-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 12).valueOf(),
            inStock: 15,
            clicked: 13,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/5.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 11).valueOf(),
            inStock: 15,
            clicked: 14,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 10).valueOf(),
            inStock: 15,
            clicked: 15,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 9).valueOf(),
            inStock: 15,
            clicked: 16,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Socket",
            createdAt: moment().subtract('day', 8).valueOf(),
            inStock: 15,
            clicked: 17,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            // image: require('../assets/frontendimages/5.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 7).valueOf(),
            inStock: 15,
            clicked: 18,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 6).valueOf(),
            inStock: 15,
            clicked: 19,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            // image: require('../assets/frontendimages/4.png'),
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 5).valueOf(),
            inStock: 15,
            clicked: 20,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 4).valueOf(),
            inStock: 15,
            clicked: 21,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/04/Diaphragm-Pumps-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 3).valueOf(),
            inStock: 15,
            clicked: 22,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/Grundfos-Booster-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 2).valueOf(),
            inStock: 15,
            clicked: 23,
        },
        {
            image: "https://www.pumpstore.co.uk/wp-content/uploads/2020/01/DAB-Jetinox-300x300.png",
            price: 250,
            title: "Motor Pump",
            createdAt: moment().subtract('day', 1).valueOf(),
            inStock: 15,
            clicked: 24,
        },

    ]
}