// Auth types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADDITEMTOCART = 'ADDITEMTOCART'
export const REMOVEFROMCART = 'REMOVEFROMCART'
export const INCREMENTQTY = 'INCREMENTQTY'
export const DECREMENTQTY = 'DECREMENTQTY'
export const EMPTYCART = 'EMPTYCART'
export const ADDITEMTOWISHLIST = 'ADDITEMTOWISHLIST'
export const REMOVEFROMWISHLIST = 'REMOVEFROMWISHLIST'
export const SETLOADING = 'SETLOADING'